
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


const AdminUserManagement = lazy(() => import("./pages/AdminUserManagement.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const Collaboration = lazy(() => import("./pages/Collaboration.tsx"));
const CreateInitialAdmin = lazy(() => import("./pages/CreateInitialAdmin.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const Messages = lazy(() => import("./pages/Messages.tsx"));
const PatientChart = lazy(() => import("./pages/PatientChart.tsx"));
const PatientCharts = lazy(() => import("./pages/PatientCharts.tsx"));
const Register = lazy(() => import("./pages/Register.tsx"));
const Schedule = lazy(() => import("./pages/Schedule.tsx"));
const Settings = lazy(() => import("./pages/Settings.tsx"));
const UserSettings = lazy(() => import("./pages/UserSettings.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/admin-user-management", element: <UserGuard><AdminUserManagement /></UserGuard>},
	{ path: "/adminusermanagement", element: <UserGuard><AdminUserManagement /></UserGuard>},
	{ path: "/", element: <App />},
	{ path: "/collaboration", element: <UserGuard><Collaboration /></UserGuard>},
	{ path: "/create-initial-admin", element: <UserGuard><CreateInitialAdmin /></UserGuard>},
	{ path: "/createinitialadmin", element: <UserGuard><CreateInitialAdmin /></UserGuard>},
	{ path: "/dashboard", element: <UserGuard><Dashboard /></UserGuard>},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard>},
	{ path: "/messages", element: <UserGuard><Messages /></UserGuard>},
	{ path: "/patient-chart", element: <UserGuard><PatientChart /></UserGuard>},
	{ path: "/patientchart", element: <UserGuard><PatientChart /></UserGuard>},
	{ path: "/patient-charts", element: <UserGuard><PatientCharts /></UserGuard>},
	{ path: "/patientcharts", element: <UserGuard><PatientCharts /></UserGuard>},
	{ path: "/register", element: <UserGuard><Register /></UserGuard>},
	{ path: "/schedule", element: <UserGuard><Schedule /></UserGuard>},
	{ path: "/settings", element: <UserGuard><Settings /></UserGuard>},
	{ path: "/user-settings", element: <UserGuard><UserSettings /></UserGuard>},
	{ path: "/usersettings", element: <UserGuard><UserSettings /></UserGuard>},

];
